# zkanji TEST v1
This is a temporary name. I will refer to the program simply as zkanji below.

---

## Description

zkanji is a cross-platform, feature rich Japanese language study suite and dictionary
software. It is still alpha, meaning it's not finished nor tested. It can damage its
own data files and files created by the program. zkanji has several kanji look-up
methods, example sentences for many Japanese words, vocabulary printing, JLPT levels
indicated for words and kanji, spaced-repetition system for studying and more.

Please see the License paragraph at the end of this readme about the license and
warranty information.

---

## Compiling from source

zkanji uses Qt, so an installation of Qt with its header files and libraries must be
present on the system. I used Qt version 5.5 during initial development, but newer
versions should work as well. zkanji can be compiled with c++ compilers that are
c++11 compatible and can use Qt.

On Windows, the minimal Visual Studio version capable of compiling zkanji is VS2013.
It is recommended, and possibly required, to use the Qt add-on for Visual Studio. GNU
c++ compilers should have no problem compiling zkanji either but I haven't tested it
yet. Currently only the Visual Studio project file is included. If it is set up
correctly, zkanji should compile out of the box. (You might need to modify the file
called zkanji.vcxproj.user, to change the path to Qt)

Instructions for other OSes will be added later as I figured them out.

If the compilation was successful, you must make sure the Qt static libraries are in
place, to be able to run zkanji. (DLLs next to the executable on Windows, the .so
files at their default location on Linux.)

---

## Setting up the data files

The following files must be downloaded, before the data files can be generated by
zkanji:  
[JMdict](http://www.edrdg.org/jmdict/j_jmdict.html) in UTF-8 encoding  
[KANJIDIC](http://nihongo.monash.edu/kanjidic.html) in EUC-JP encoding  
[RADKFILE](http://users.monash.edu/~jwb/kradinf.html) also in EUC-JP.

For the example sentences data, download the complete version of the 
[Tanaka Corpus](http://www.edrdg.org/wiki/index.php/Tanaka_Corpus) in UTF-8 encoding.
The downloadable subset of Tanaka Corpus is also usable, but it's only available in
EUC-JP encoding on the site, so it must be converted to UTF-8 first with the name
`examples.utf`.

The files must be extracted from their archives and placed next to the files in the
dataimports folder. (Any folder is valid, as long as the files from dataimports are
also copied there.)

To generate the data files for zkanji, you need to create a folder called data next
to the executable, and run the compiled program with command line options.

The command line option for generating the dictionary data files is:  
`-i [path]`  
Path must point to the folder with the files from dataimports. (Not the newly created
data folder.)

To generate the example sentences data file, use the command line option:  
`-e [path]`  
The `examples.utf` file must be on the passed path.

The options can be combined. For example on Windows the following line will create
every required data file for zkanji to run:
`zkanji.exe -ie C:\projects\zkanji\dataimports`

If the data files are generated successfully, zkanji will start. See the next
section for instructions.

---

## Running for the first time

When run for the first time, zkanji might offer to run normally or in portable mode.
For this test version, it's recommended to start the program in portable mode, to
save the data files next to the executable in its data folder. (The user must have
read/write access to the files in the folder.)

The program will offer to import user data from zkanji v0.731.

---

## License

Copyright 2017 Sólyom Zoltán
z-one AT-SIGN free mail DOT hu (Remove the spaces and replace parts accordingly.)

zkanji TEST v1 is licensed under the terms of the GNU GPLv3. See the LICENCE file for
details. The files in folders are released with the same license, unless otherwise
stated in the files themselves.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

An earlier program called zkanji, released before 2014 used a different license,
which is not applicatble to this version.

---

## Credits

Qt is used for the cross platform user interface. On Windows (which currently is the
only platform,) zkanji is linked dynamically with the Qt DLLs


